week-4/schedule.md

Matches the general structure of the Week 3 schedule:
1. Day 1: general week intro, leading into more complex workshop
1. Day 2: design burst, then another more specific workshop
1. Day 3: morning challenge on stuff they might need in their project

Add initial Week 4 Node schedule

---

week-8/schedule.md

I've moved mocking from Week 7 MC to here since it's a better fit (they should be testing this frontend without worrying about the separate backend, which should already have tests)
Since this week is mostly stuff they already know the basics of I figured we could teach some more interesting client-side stuff. So I've added both ES Modules and basic client-side routing, both of which will make their projects easier and more realistic.
Let me know if you think that's too much new/weird stuff!

Add Week 8 schedule

---

README.md

Adding in the generic schedule that we can present to FAC18 alongside a list of topics for each week.

Add a generic schedule for weeks1-8 alongside a table of topics

---

week-2/schedule.md

https://github.com/oliverjam/real-world-fetch
- Covers stuff you need to use `fetch` in a real app
- Error handling for non-200 HTTP responses
- `fetch` options:
- method
- body
- Handling user input with forms
- `preventDefault()`
- Various ways to access form input data
I'm not sure if it needs a proper "workshop" bit at the end. Some of the interspersed "challenges" are more involved and are basically what I'd want from a "workshop" anyway.
I also swapped the first-class functions and learn-fetch-promises workshops around, since we should cover callbacks before promises.
Closes #35

Add week 2 "Real world fetch" workshop

---

README.md
src/_data/eleventyComputed.js
src/about.md

- Move the previous README contents to published `/about/` page.
- Add regular README describing how to run the project etc
I think it makes more sense for the "who can use this?" stuff to be in an actual published page, and for the readme to be reserved for people viewing on GitHub (and so primarily code-related).

Add about page

---

.eleventy.js
package-lock.json
package.json
src/_data/defaultSchedule.yml
src/_includes/course.11ty.js
src/_includes/default.11ty.js
src/_includes/schedule.11ty.js
src/_includes/standalone.11ty.js
src/_includes/syllabus.11ty.js
src/_includes/topics.11ty.js
src/_includes/workshop.11ty.js
src/course/syllabus/testing/schedule.md
src/styles/index.css
src/styles/partials/layout.css
src/styles/partials/main.css
src/styles/partials/navigation.css
src/styles/partials/timetable.css

I think this is both a lot easier to write/maintain for us, and a lot nicer to read for the cohort.
There's a `_data/defaultSchedule.yml` with the repeated stuff (check-in, lunch, presentations) etc, and then a `schedule.md` in each week's folder. They get merged together using the start time as the uniqueness ID, preferring the week schedule. So if the week schedule has something at 11:00 it overrides whatever might have been in the default at that time.
The data is structured like this:
```yml
schedule:
monday:
- start: 10:00
end: 10:30
name: Intro presentation
type: slides
url: "/intro-pres"
- start: 10:30
end: 11:30
name: Build a testing library
type: workshop
url: "/testing-lib"
```

New schedule format

---

src/_data/defaultSchedule.yml
src/_includes/schedule.11ty.js
src/course/syllabus/teamwork/schedule.md

- Add new Week 1 schedule
- Fix default schedule overriding logic. It now correctly removes whatever was in the default schedule slot if a week schedule has an entry that overlaps at all. E.g. if you schedule something for 13:30 it'll remove lunch for that day. The downside is you have to manually re-include default stuff if you are tweaking times a bit (e.g. "Respond To Issues on Friday here).

Week 1 schedule

---

src/course/syllabus/server-side-app/schedule.md

Just to make sure that we're being clear about what is happening this afternoon! Changing the link from an employment mentor talk to the link for code writing exercises

Update employment mentors to interview prep

---

src/workshops/css-layout/index.md
src/workshops/css-layout/starter-files/challenge-4/index.html
src/workshops/css-layout/starter-files/challenge-4/solution.html

Hotlinking to weird Instagram URLs was always a mistake 😅
(each image has a 1px different size to force Unsplash to return a different one, otherwise you get a grid of the same dog)

Fix broken images in CSS Layout challenge

---

src/course/syllabus/full-stack-app/schedule.md

https://learn.foundersandcoders.com/course/syllabus/full-stack-app/schedule/
https://nextjs.org/learn/basics/ -> https://nextjs.org/learn/

Next.js link returning 404

---

src/course/handbook/learning-circles.md
src/course/syllabus/pre-app-7/schedule.md
src/course/syllabus/pre-app-8/schedule.md

Links need to point to final built HTML pages rather than `.md` content files. The easiest way is to use relative URLs to reference sibling pages (e.g. `thing.md` -> `../thing/`)

Fix links that reference source files

---

src/workshops/node-error-handling/index.md

having unhandledRejection in camelcase in the example and then all lowercase in the explainer text below could be confusing, node expects it to be camelcase right?

change unhandledRejection to camelcase

---

src/_includes/course.11ty.js
src/course/handbook/project-presentations.md
src/course/handbook/projects.md

Relates #549 #497 and https://github.com/foundersandcoders/tasks/issues/2
- Removed some old info from the projects document in the handbook (eg teams are stuck on the wall)
- Added github workflow guidance and team workflow guidance
- Moved project presentation guidance to a separate document

add new projects doc, move project presentation guidance

---

src/_data/defaultSchedule.yml
src/course/syllabus/apprenticeship/authentication/schedule.md
src/course/syllabus/apprenticeship/client-side-app/schedule.md
src/course/syllabus/apprenticeship/database/schedule.md
src/course/syllabus/apprenticeship/full-stack-app/schedule.md
src/course/syllabus/apprenticeship/server-side-app/schedule.md

The cohort have said that they much prefer role circles to be part of the standup on the second day, once they've had a chance to work on their projects a little.
Database week is a weird one because of the web science talk, and for the two weeks  with three day projects I've kept it on wednesday as that is day 2. (next and server side week)

move role circles to thursday mornings

---

src/workshops/session-auth/starter-files/package-lock.json
src/workshops/session-auth/starter-files/package.json
src/workshops/session-auth/starter-files/solution/database/connection.js
src/workshops/session-auth/starter-files/solution/server.js
src/workshops/session-auth/starter-files/workshop/database/connection.js
src/workshops/session-auth/starter-files/workshop/server.js

Remove references to `dotenv.config()` to be consistent with DB week—it's better to just load dotenv in dev/test scripts, since we rely on the Heroku environment for prod env vars.

Refactor session workshop

---

src/course/syllabus/apprenticeship/full-stack-app/project.md

Yarn is the default installer for create-next-app
FAC24 ran into a yarn.lock file after creating their next project - was confusing as they hadn't encountered yarn before.
I've updated this to pass in a flag to explicitly install extra dependencies for create-next-app with npm instead of yarn.

Add flag to use npm instead of yarn

---

src/_includes/workshop.11ty.js
src/learn/learn.json
src/learn/server/index.md
src/styles/partials/components.css
src/workshops/node-express-server/index.md

I've created a new `/learn` directory/URL path to group the new consolidated resources for each week. That way we can keep the old workshops in place for anyone who wishes to refer back to them from previous cohorts.
I'm planning on merging a PR for each week's learning workshop, then updating the schedule all at once. Each workshop will also have an accompanying "challenge" repo, which will effectively just be starter code with a series of small challenges and accompanying unit tests.
Express was an easy one to start with, since it was effectively one long workshop anyway. This PR primarily just cleans it up and adds a few things:
1. Introduce very simple testing using the new built-in Node test runner (#618)
1. Introduce env vars and setting the server port (#422)
Relates #716

Consolidate server workshops

---

src/learn/server/index.md

I realised the Node intro needed an explanation for importing with `require`. This used to be in the npm intro, but that was amended so it could be delivered in the Skills Bootcamp in a frontend context.

Explain Commonjs modules

---

src/_data/defaultSchedule.yml
src/course/syllabus/apprenticeship/database/schedule.md

They should all be at 12 now.
Removed from default schedule since each week needs its own.

Fix morning challenge schedule conflict

---

src/_includes/workshop.11ty.js

This will hopefully encourage learners to report typos/bugs etc.
fix #463 (can't believe it took so long)
We used to get a lot more engagement back when workshops were just consumed directly on GiHub. But the last couple of years we've had basically no issues raised, even for basic stuff like typos. Hopefully this will help shift that a bit.
It auto-populates a GitHub issue with the workshop in the title and the "feedback" label so we can easily filter for them.

Add GitHub issue feedback link to workshops

---

src/course/syllabus/apprenticeship/full-stack-app/project.md
src/course/syllabus/apprenticeship/full-stack-app/resources.md
src/course/syllabus/apprenticeship/full-stack-app/schedule.md

My compromise solution to hosting was to give them the option to stick with Heroku if they want to focus on Next and don't mind the lack of DB persistence, otherwise they can try out Fly. The Fly docs are pretty self-explanatory (you run `fly launch` in your app directory and it auto-generates everything you need) so I'm not sure if we need more guidance than that.
Fix #723 
Fix #732

Make Next.js project fit new curriculum.

---

src/course/syllabus/projects/TFB-design/schedule.md
src/course/syllabus/projects/in-house-build-1/schedule.md

We cld also use the same slide deck for TfB Definition intro as was used for the In-house - the only real diff is the screenshots of the Miro that I added in.

Combine Project Planning and Code Planning; Update links.

---

src/course/syllabus/developer/full-stack-app/project.md

When I wrote this project I intended learners to keep using the knowledge from the prior weeks, so storing info server-side using cookies + DB. I imagine a lot of learners have found it easier to use localStorage though since Next doesn't exactly make it obvious how to do cookie stuff.

Clarify Next project could use cookies instead of localstorage

---

src/workshops/node-npm-intro/starter-files/asciiArtGenerator.js
src/workshops/node-npm-intro/starter-files/package.json

Strangely the node-npm-intro workshop has no starter files so I have added some here. More updates to come for this particular workshop but I want these files in the main repo so I can test the script to download the files is working.

add starter files to node-npm-intro workshop

---

src/_data/defaultSchedule.yml
src/course/syllabus/developer/authentication/schedule.md
src/course/syllabus/developer/introduction/schedule.md
src/course/syllabus/developer/projects/TFB-build-1/schedule.md
src/course/syllabus/developer/projects/TFB-build-1/spikes.md
src/course/syllabus/developer/projects/TFB-build-2/schedule.md
src/course/syllabus/developer/projects/TFB-build-2/spikes.md
src/course/syllabus/developer/projects/TFB-design/schedule.md
src/course/syllabus/developer/projects/in-house-build-1/schedule.md
src/course/syllabus/developer/projects/in-house-build-1/spikes.md
src/course/syllabus/developer/projects/in-house-build-2/schedule.md
src/course/syllabus/developer/projects/in-house-build-2/spikes.md
src/course/syllabus/developer/projects/in-house-design/resources.md
src/course/syllabus/developer/projects/in-house-design/schedule.md
src/course/syllabus/tfb/week 12/resources.md
src/workshops/node-npm-intro/index.md
src/workshops/scope-challenge/index.md

Since the handbook is now being outsourced there are a number of outdated links in the ft schedule. I have tried to update all so that they link to the notion page.

replace handbook archive links with notion docs

---

src/course/syllabus/foundation/pre-course/schedule.md

Updated dates for spring term unschool dates

---

src/_includes/resources.11ty.js

On medium viewports the content column ends up way too small because of the empty space left for the (nonexistent) sidebar nav.
Workshops don't have a sidebar, so we can just not use this layout for them.
This is a quick fix so the content is no longer centre-aligned, but I think that's fine as it's way more usable for people with medium screens.
https://github.com/foundersandcoders/coursebook/assets/9408641/643fe3cc-39b0-4cb2-8fa8-7111bdd461b4
https://github.com/foundersandcoders/coursebook/assets/9408641/5901fd0d-fc06-4449-8e34-ab5d6b24a32c

Stop workshop layouts getting squished
