week-6/learning-outcomes.md
I skipped Week 5 for now as DBs aren't my favourite. Hopefully we can establish this structure so each week can mirror it.
```markdown
## Developer Toolkit LOs
```
=> Scaffold Week 6 (Authentication) Learning Outcomes

week-5/learning-outcomes.md
=> Scaffold Week 5 (Databases) Learning Outcomes

week-2/schedule.md, week-3/schedule.md
There are quite a lot of missing resources for this week that should be prioritised. I've got a decent idea of what I want them to look like though.
Also I moved the DOM manipulation morning challenge from Week 3 to this week because it's in the learning outcomes and is better to have as early in the course as possible. I've replaced it in Week 3 with a yet-to-be-created "Function scope & closures" MC, which fits better with Week 3's learning outcomes anyway.
=> Create Week 2 schedule

week-5/project.md, week-5/schedule.md
I've added the UI components/elements design burst to go with the design learning outcome (UI components) that we agreed for this week. 
The technical spike afternoon is shorter than usual, so it's perhaps worth finding some quite specific topics for students to spike on.
Otherwise, everything is similar to the current db week.
=> Create week 5 schedule

week-7/learning-outcomes.md, week-7/schedule.md
I removed the animated menu design LO in favour of wireframing (what we agreed before, and what we have an existing Design Burst for).
This week currently has the most missing material (i.e. all of it) since the entire concept is new. Exciting!
=> Week 7 schedule

week-6/project.md, week-6/schedule.md
Creates the schedule.md auth week schedule doc and the project.md project description doc.
**GAPS**
- There's no 30 min challenge to accompany the typography design burst presentation
- Research afternoon topics
=> Create week 6 schedule

.gitbook.yaml, SUMMARY.md
This should make the nav on Gitbook a lot nicer
https://docs.gitbook.com/integrations/github/content-configuration
=> Add config for gitbook navigation

week-2/schedule.md
https://github.com/oliverjam/learn-fetch/
This is mostly adapted from the Learn Promises workshop that FAC18 did in Week 7. The main change is removing all the Node stuff and teaching `fetch` instead. I've also interwoven little "check in" challenges where they have to go and write a line of code that they just learnt to make sure they're paying attention.
- Introduces `fetch`
- Introduces promises
- Explains how to access promise values with `.then()`
- Covers chaining `.then()`s
- Catching errors with `.catch()`
- `fetch` best practices
- e.g. it won't throw error on non-200 status code
- Creating your own promises
Closes #32
=> Add new fetch workshop

week-2/schedule.md
https://github.com/oliverjam/first-class-functions
Same style as the last one, which I'm enjoying (putting little check-in "challenges" as they read, then one harder "workshop" at the end)
I kinda want to get something like [this example](https://github.com/foundersandcoders/master-reference/issues/433) in there too, not sure.
Closes #33
=> Add First-class Functions workshop

week-1/schedule.md
**Link:** https://github.com/bobbysebolao/learn-css-variables
**Topics covered:**
- Using CSS variables to control colour in a UI
- Toggling CSS variable colour values in JS to create different colour themes for a UI
This workshop follows on from the preceding design burst slides (will share these shortly) on using colour in UI.
Feedback welcome!
Closes #40
=> Learn CSS variables/colour in UI challenge

week-2/schedule.md
This isn't perfect but it's fine for now considering how much other new stuff we need to cover. Not sure how I forgot to link it when I made this schedule before
=> Add existing DOM morning challenge

week-2/schedule.md
Not quite polished yet but getting there
https://hackmd.io/@oli/Hy2LcbNm8
Closes #31
=> Add HTTP intro slides

week-3/schedule.md
https://hackmd.io/@oli/Sy7cA4TXI
Feels kinda short but I think it covers everything I'd want them to be thinking about at this point.
Fixes #70
=> Add intro slides to testing week

week-3/schedule.md
https://github.com/oliverjam/learn-unit-testing
This is only going to be a 1 hour workshop because there's just no way to fill 2 hours here. I'm writing a follow up integration testing one for the second hour.
The leap year challenge was designed to replace fizzbuzz with something a bit more interesting.
Fixes #37
=> Add link to week 3 unit testing workshop

SUMMARY.md, documents/code-of-conduct.md, documents/code-review.md, documents/house-rules.md, documents/pair-programming.md, documents/projects.md, documents/retrospectives.md, documents/spikes.md, week-1/schedule.md
=> Week 1 fixes

week-1/schedule.md
**Link:** http://facresources.com/
See new slides for the week 1 design bust under the 'Design burst' section.
Feedback welcome!
=> Update week 1 schedule with link to new design burst slides

week-2/schedule.md
**Link:** https://github.com/bobbysebolao/learn-layout-spacing/blob/master/readme.md
This workshop follows on from the preceding design burst slides (still to be made) that go over Steve Schoger's layout and spacing design principles
Topics covered:
- Steve Schoger's layout and spacing design principles
- Using CSS flexbox to create 
I'm thinking of adding a stretch goal of using a media query to change the layout for screens smaller than 700px (using flex-direction: column). 
Feedback welcome!
Closes #34
=> Learn layout and spacing/CSS flexbox

week-2/project.md
~This project is quite open-ended, so I'm not sure we can provide specific user-stories. Maybe we should ask them to write their own stories once they've decided what they want to build?~  I ended up doing generic stories for what we can.
=> Add week 2 project guide

week-3/schedule.md
https://github.com/oliverjam/learn-integration-testing
- Unit testing becomes 1 hour
- Integration testing now takes up the 2nd hour
=> Add integration testing workshop

LICENSE
Plaintext license from here: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode.txt
HTML version here: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
Fixes #66
=> Add CC-BY-NC-SA 4.0 license

week-3/schedule.md
https://github.com/oliverjam/tdd-array-methods
Introduces TDD and has them ping pong writing tests then code for each array method (`map`, `filter`, `every`, `some`, `reduce` and `flat`)
Fixes #41
=> Add TDD array methods workshop

week-3/project.md
How do we feel about providing the test shells for them to fill in?
=> Add week 3 project guide

week-3/schedule.md
https://github.com/oliverjam/js-scope-challenge
Fixes #42
=> Add Week 3 scope morning challenge

week-3/schedule.md
**Link:** https://github.com/bobbysebolao/learn-css-grid
Raising this PR now as I didn't get to do it last week.
This workshop covers the week 3 design burst topic of grid layouts and CSS Grid.
Feedback welcome, happy to make edits this week!
I think asking the students to write two media queries and new grid layouts as the stretch goal might be asking too much in just 1 hour...
(ps. I noticed that there isn't an issue open for this design burst, it's also not on the GitHub project board, might be worth adding)
=> Learn CSS Grid/grid layouts workshop

week-4/schedule.md
I got carried away writing a quick intro to Node and ended up writing a pretty much complete guide to Node 😅 
1. Node Introduction: wtf is Node, how do I install it, how do I run it, what's a `require`?
https://github.com/oliverjam/node-introduction
1. Node HTTP Servers: creating a web server, routes, 404s
https://github.com/oliverjam/node-http-server
1. Node File Servers: `fs`, reading and serving files, error-first callbacks, `content-type`s
https://github.com/oliverjam/node-file-server
Also some scheduling changes: spike research moved to Monday afternoon, with presentations on Tuesday morning. Tech For Better moves to Tuesday afternoon (although it probably isn't happening this cohort)
Fixes #43
=> Week 4 schedule

week-4/project.md, week-4/schedule.md, week-4/spikes.md
Add spikes and project intro.
I also moved the npm intro to Monday because we had more spare time there. It'll be better for them to see that before they do spikes, cause they'll see package.jsons and npm installs all over the place when they're researching
=> Week 4 spikes & project

documents/spikes.md
=> Amend guidance on spike presentations

week-5/learning-outcomes.md, week-5/schedule.md
=> Week 5 schedule

week-5/project.md
=> Fix a subhead markup glitch

week-5/spikes.md, week-6/project.md, week-6/schedule.md, week-6/spikes.md
Add new [password security](https://github.com/oliverjam/learn-password-security) and [validation workshop](https://github.com/oliverjam/learn-form-validation) and morning challenge (yet to be written)
Also add the spikes and project guide
=> Finalise week 6 schedule

week-7/schedule.md
=> Week 7 schedule updates

week-8/schedule.md
- [Learn ES Modules](https://github.com/oliverjam/learn-es-modules)
- [Learn DOM rendering](https://github.com/oliverjam/learn-dom-rendering)
- [Learn client-side routing](https://github.com/oliverjam/learn-client-side-routing)
=> Add Week 8 Monday workshops

week-8/schedule.md
=> Add final workshop to Week 8 schedule

week-8/schedule.md
https://github.com/oliverjam/css-pseudo-element-challenge
=> Add week 8 morning  challenge

week-10/learning-outcomes.md, week-10/project.md, week-10/schedule.md
=> Move React Week resources into coursebook

documents/projects.md, week-1/schedule.md, week-2/schedule.md
=> Add velocity to project presentation advice

week-10/schedule.md
=> Add FAC19 specific scheduling to React Week

SUMMARY.md, design-week/learning-outcomes.md, design-week/project.md, design-week/schedule.md
- Add schedule for Design Week
- Add docs for learning outcomes and project
=> Design week

design-week/schedule.md
=> Add build sprint intro link

SUMMARY.md, projects/mentor-roles.md, projects/schedule.md, projects/student-roles.md, projects/w11-schedule.md, projects/w12-schedule.md, projects/w13-schedule.md, projects/w14-schedule.md, projects/w15-schedule.md, projects/w16-schedule.md
=> Projects Section

documents/precourse.md
=> Fix JS calculator deadlink

README.md
We should make it clear that we'd love for others to use our curriculum as a learning resource. However we also need to explain exactly how our license works so there is no confusion
Fixes #168
=> Add guidance for others using our curriculum

SUMMARY.md, projects/tfb-presentation.md, projects/w16-schedule.md
Still unsure of the links - have added them to Summary.md, this is the only difference I can see between the routing here compared to Precourse.md 🤷‍♀️ 
Have added in some guidance for TFB presentations
=> Add presentation guidance

documents/one-day-projects.md
=> One-day projects README

README.md
=> Fix broken topic links in readme

README.md
Relative links weren't working, have updated these to external ones
=> Update links to external

curriculum/teamwork-and-toolkit/schedule.md
small updates to timings for clarity
=> update week one timings

curriculum/http/spikes.md
=> Clean up Week 2 spikes

README.md, curriculum/http/schedule.md
- updated day end timings in default to 17:45
- updated Friday timings to accommodate SGCs and user manual updates
- fixed a link in week 2
- shuffled week 2 (t4b and spikes) with fetch workshop slightly spanning lunch since the fetch workshop is juicy.
- updated links to workshop lengths
=> timings and update to week 2 structure

curriculum/testing/schedule.md
still tbc on tuesday afternoon
=> week three

curriculum/http/project.md
Clarify how API keys work
Relates #223
=> Remove api key project criteria from http week

curriculum/databases/schedule.md
We never actually did the old one for FAC19, I just never got time to replace it. The new one covers deploying Postgres to Heroku, then some fun advanced SQL stuff to practice joins and sub queries.
=> Swap old DB MC for new one

projects/design-week/schedule.md
=> FAC20 DW Schedule

curriculum/fullstack-app/project.md, curriculum/fullstack-app/schedule.md
Also updated assessment criteria for cross-browser testing.
The project references client side routing in the summary and assessment criteria
Also currently no additional resources are linked
These are from FAC19's SPA resources folder:
[How single page applications work](https://blog.pshrmn.com/how-single-page-applications-work/)
[Single page applications and the server](https://blog.pshrmn.com/single-page-applications-and-the-server/)
=> update spa schedule

curriculum/single-page-app/project.md, curriculum/single-page-app/schedule.md
Plus half hour for student projects
=> Add SPA week day 2 workshops

README.md
=> Fix broken link on readme

curriculum/react/resources.md, curriculum/react/schedule.md
Not sure why I didn't copy the resources over with the rest of the week's content ages ago.
Also we need to use my fork of Sofia's workshop as there are some fixes in a PR that isn't merged yet.
=> React week resources

projects/student-projects/build-1.md, projects/tech-for-better/design.md
Jack and Gregor to discuss and finalise
=> Update schedules to include TFB

README.md
- Add links to clone/forks docs
- Clarify that using the curriculum isn't the same as graduating
Fix #219
=> Clarify for self learners

projects/tech-for-better/build-1.md, projects/tech-for-better/build-2.md, projects/tech-for-better/design.md
Jack and Gregor to review on Monday
=> Updates to schedule

precourse/system-requirements.md
Didn't want to get too prescriptive so just listed the stuff that actually matters. If I've missed anything off you think is important let me know
Fix #293
=> Add minimum system requirements to precourse

handbook/debugging.md
I starting writing a "how to ask for help guide" but it ended up getting too technical so I split the debugging part out into this
=> First draft of debugging advice

handbook/coaching.md
Addresses #309.
Tidied up over the weekend.
=> Guidelines for coaching sessions

handbook/coaching.md
Just wanted to emphasise the third role in a 3-person group as potentially involving a bit of googling
=> Very minor change to coaching text

curriculum/authentication/schedule.md, curriculum/databases/schedule.md, curriculum/http/schedule.md, curriculum/node/schedule.md, curriculum/react/schedule.md, curriculum/rest-apis/schedule.md, curriculum/single-page-app/schedule.md, curriculum/teamwork-and-toolkit/schedule.md, curriculum/testing/schedule.md
=> add live code review

curriculum/http/schedule.md, curriculum/teamwork-and-toolkit/schedule.md, curriculum/testing/schedule.md
=> "Speaker" -> "Roundtable" on Fridays in first three weeks

src/course/handbook/installation.md
I wanted to document a couple of recurring problems I saw while they're still fresh in my mind
=> Installation troubleshooting

src/_includes/course.11ty.js, src/course/handbook/mentor-roles.md
fixes #325 
Outlines what to expect from each type of mentor
=> Add mentor roles Doc

src/course/syllabus/api/project.md
=> Add documentation to API week acceptance criteria

src/course/handbook/course-rules.md, src/styles/partials/main.css
Replaces the old course rules with new improved ones. Less practically focused and more in line with our values as an org
=> Social rules

src/lollipop/index.html, src/styles/partials/components.css, src/styles/partials/utilities.css
This is the new and improved version of the one I made for FAC19.
Now with:
- Actually random shuffling! No more bias towards the same names over and over
- Persisting names in the URL so you can share
- Permanently available at learn.foundersandcoders.com/lollipop/
https://user-images.githubusercontent.com/9408641/110633292-7efa1080-81a0-11eb-8259-7aa3b9046b0c.mp4
=> New Lollipop app

src/course/syllabus/database/spikes.md
=> Replace broken GitHub Actions spike resource

src/_data/defaultSchedule.yml, src/course/syllabus/api/schedule.md, src/course/syllabus/http/schedule.md
I got mixed up between http and api so this is probably not the most useful week to have done for my trial 😅 
Just wanted to check I was on the right track before I do the rest.
=> Add schedule for API week

src/course/syllabus/http/schedule.md
Small update to add the Q+As, which for now should be the only change to next week
=> Add Q+As to HTTP schedule

.eleventy.js, src/_includes/shortcodes/index.js, src/course/syllabus/http/schedule.md, src/workshops/real-world-fetch/index.md, src/workshops/real-world-fetch/starter-files/solution.html, src/workshops/real-world-fetch/starter-files/workshop.html
- Add `{% solution %}` shortcode to make authoring collapsible solution sections easier
=> HTTP week links

src/course/syllabus/http/schedule.md, src/styles/partials/syntax-highlighting.css, src/workshops/learn-fetch/index.md, src/workshops/promise-practice/index.md, src/workshops/promise-practice/starter-files/challenge-1/index.html, src/workshops/promise-practice/starter-files/challenge-1/solution.html, src/workshops/promise-practice/starter-files/challenge-2/index.html, src/workshops/promise-practice/starter-files/challenge-2/solution.html
The callback/first-class functions workshop was delivered in the pre-course. This left a gap to fill, which I've done with an extra workshop practicing using promises to avoid callback hell (chaining .thens etc)
=> HTTP week reshuffle

src/course/syllabus/http/schedule.md, src/course/syllabus/teamwork/schedule.md, src/course/syllabus/testing/schedule.md
Changed interview prep to after lunch on Tuesday for HTTP and Testing weeks
Also swapped live code review to earliest slot for Teamwork week so that we don't forget to change it later.
=> Adjust interview prep

src/_includes/shortcodes/index.js, src/styles/partials/utilities.css, src/workshops/promise-practice/starter-files/challenge-1/index.html, src/workshops/real-world-fetch/index.md, src/workshops/real-world-fetch/starter-files/solution.html
Replaced the example APIs with my own purpose-built one (the others had CORS errors and weird things). Also removed a kinda pointless challenge section and cleaned up the examples a bit.
=> Clean up Real World Fetch workshop

src/course/syllabus/http/schedule.md, src/workshops/dom-challenge/index.md, src/workshops/dom-challenge/starter-files/challenge/dom.js, src/workshops/dom-challenge/starter-files/challenge/index.html, src/workshops/dom-challenge/starter-files/challenge/style.css, src/workshops/dom-challenge/starter-files/solution/dom.js, src/workshops/dom-challenge/starter-files/solution/index.html, src/workshops/dom-challenge/starter-files/solution/style.css
The old one is really old and kinda outdated. This keeps the same concepts but tries to mostly teach modern methods.
=> DOM morning challenge

src/course/syllabus/http/project.md, src/styles/partials/reset.css
- Fix Markdown bug
- Recommend teams move on from bad APIs after 20 minutes
- Remove bad recommended APIs (e.g. with no CORS)
- Clean up table (remove a lot of superfluous text so it's not so long)
- Unrelated, fix broken giant checkboxes across the site while I was there 🙃
=> Clean up HTTP Project

src/course/syllabus/testing/schedule.md, src/styles/partials/syntax-highlighting.css, src/workshops/learn-integration-testing/index.md, src/workshops/learn-integration-testing/starter-files/solution/index.html, src/workshops/learn-integration-testing/starter-files/solution/index.js, src/workshops/learn-integration-testing/starter-files/solution/index.test.js, src/workshops/learn-integration-testing/starter-files/test-helpers.js, src/workshops/learn-integration-testing/starter-files/workshop/index.html, src/workshops/learn-integration-testing/starter-files/workshop/index.js, src/workshops/learn-testing/index.md, src/workshops/learn-testing/starter-files/solution.html, src/workshops/learn-testing/starter-files/workshop.html, src/workshops/learn-unit-testing/index.md, src/workshops/learn-unit-testing/starter-files/solution/index.html, src/workshops/learn-unit-testing/starter-files/solution/index.js, src/workshops/learn-unit-testing/starter-files/solution/index.test.js, src/workshops/learn-unit-testing/starter-files/test-helpers.js, src/workshops/learn-unit-testing/starter-files/workshop/index.html, src/workshops/learn-unit-testing/starter-files/workshop/index.js
Transfer over Monday's workshops and add to schedule.
Also make code blocks look a lil nicer with a language label :)
=> Testing week workshops

src/course/syllabus/testing/project.md, src/course/syllabus/testing/schedule.md, src/course/syllabus/testing/spikes.md, src/workshops/scope-challenge/index.md, src/workshops/scope-challenge/starter-files/challenge/burst.css, src/workshops/scope-challenge/starter-files/challenge/burst.js, src/workshops/scope-challenge/starter-files/challenge/index.html, src/workshops/scope-challenge/starter-files/challenge/other.js, src/workshops/scope-challenge/starter-files/challenge/utils.js, src/workshops/scope-challenge/starter-files/solution/burst.css, src/workshops/scope-challenge/starter-files/solution/burst.js, src/workshops/scope-challenge/starter-files/solution/index.html, src/workshops/scope-challenge/starter-files/solution/utils.js, src/workshops/tdd-array-methods/index.md, src/workshops/tdd-array-methods/starter-files/solution/index.html, src/workshops/tdd-array-methods/starter-files/solution/index.js, src/workshops/tdd-array-methods/starter-files/solution/index.test.js, src/workshops/tdd-array-methods/starter-files/solution/tdd-explanation.js, src/workshops/tdd-array-methods/starter-files/test-helpers.js, src/workshops/tdd-array-methods/starter-files/workshop/index.html, src/workshops/tdd-array-methods/starter-files/workshop/index.js, src/workshops/tdd-array-methods/starter-files/workshop/index.test.js
=> Add missing Testing week workshops

src/course/syllabus/testing/schedule.md
=> Add feedback survey to testing week

src/course/syllabus/http/learning-outcomes.md, src/course/syllabus/teamwork/learning-outcomes.md, src/course/syllabus/teamwork/schedule.md, src/course/syllabus/testing/learning-outcomes.md
These were a little out-of-date or overly verbose. I think fewer is better so people actually read them
=> Clean up first-half learning outcomes

src/course/revision-checklist.md, src/styles/partials/syntax-highlighting.css
=> Add revision checklist

src/course/mini-projects.md
=> Add mini project explainer

src/course/syllabus/server/schedule.md, src/workshops/server-side-forms/index.md
So mentors can see what's going to be delivered there
=> Add scaffold for server forms workshop

src/course/syllabus/server/schedule.md
Editing the schedule to include Anni's talk and changing the interview prep to chatting about mentoring for meetups.
=> Edit Tuesday Server week

src/_includes/course.11ty.js, src/course/handbook/role-circles.md, src/course/syllabus/api/schedule.md
=> Role circles

src/course/syllabus/authentication/schedule.md, src/workshops/password-security/index.md, src/workshops/password-security/starter-files/package-lock.json, src/workshops/password-security/starter-files/package.json, src/workshops/password-security/starter-files/solution-bcrypt/database/db.js, src/workshops/password-security/starter-files/solution-bcrypt/handlers/home.js, src/workshops/password-security/starter-files/solution-bcrypt/handlers/logIn.js, src/workshops/password-security/starter-files/solution-bcrypt/handlers/signUp.js, src/workshops/password-security/starter-files/solution-bcrypt/server.js, src/workshops/password-security/starter-files/solution-hashing/database/db.js, src/workshops/password-security/starter-files/solution-hashing/handlers/home.js, src/workshops/password-security/starter-files/solution-hashing/handlers/logIn.js, src/workshops/password-security/starter-files/solution-hashing/handlers/signUp.js, src/workshops/password-security/starter-files/solution-hashing/server.js, src/workshops/password-security/starter-files/solution-random-salt/database/db.js, src/workshops/password-security/starter-files/solution-random-salt/handlers/home.js, src/workshops/password-security/starter-files/solution-random-salt/handlers/logIn.js, src/workshops/password-security/starter-files/solution-random-salt/handlers/signUp.js, src/workshops/password-security/starter-files/solution-random-salt/server.js, src/workshops/password-security/starter-files/solution-salting/database/db.js, src/workshops/password-security/starter-files/solution-salting/handlers/home.js, src/workshops/password-security/starter-files/solution-salting/handlers/logIn.js, src/workshops/password-security/starter-files/solution-salting/handlers/signUp.js, src/workshops/password-security/starter-files/solution-salting/server.js, src/workshops/password-security/starter-files/workshop/database/db.js, src/workshops/password-security/starter-files/workshop/handlers/home.js, src/workshops/password-security/starter-files/workshop/handlers/logIn.js, src/workshops/password-security/starter-files/workshop/handlers/signUp.js, src/workshops/password-security/starter-files/workshop/server.js
- Schedule
- Password workshop
=> Auth week start

src/course/handbook/glossary.md, src/course/handbook/learning-circles.md, src/course/handbook/problem-solving-questions.md
=> New learning circles copy

src/course/syllabus/client-side-app/schedule.md, src/workshops/dom-rendering/index.md, src/workshops/dom-rendering/starter-files/solution-create-element/app.js, src/workshops/dom-rendering/starter-files/solution-create-element/create-element.js, src/workshops/dom-rendering/starter-files/solution-create-element/dogs.js, src/workshops/dom-rendering/starter-files/solution-create-element/index.html, src/workshops/dom-rendering/starter-files/solution-inner-html/app.js, src/workshops/dom-rendering/starter-files/solution-inner-html/dogs.js, src/workshops/dom-rendering/starter-files/solution-inner-html/index.html, src/workshops/dom-rendering/starter-files/solution-templates-in-js/app.js, src/workshops/dom-rendering/starter-files/solution-templates-in-js/dogs.js, src/workshops/dom-rendering/starter-files/solution-templates-in-js/index.html, src/workshops/dom-rendering/starter-files/solution-templates/app.js, src/workshops/dom-rendering/starter-files/solution-templates/dogs.js, src/workshops/dom-rendering/starter-files/solution-templates/index.html, src/workshops/dom-rendering/starter-files/workshop/dogs.js, src/workshops/dom-rendering/starter-files/workshop/index.html
=> More Week 8

src/course/syllabus/client-side-app/project.md, src/course/syllabus/client-side-app/schedule.md, src/workshops/react-refactor-classes/index.md, src/workshops/react-refactor-classes/starter-files/.babelrc, src/workshops/react-refactor-classes/starter-files/.eslintrc, src/workshops/react-refactor-classes/starter-files/__tests__/Counter.test.jsx, src/workshops/react-refactor-classes/starter-files/__tests__/Keyboard.test.jsx, src/workshops/react-refactor-classes/starter-files/__tests__/Pokemon.test.jsx, src/workshops/react-refactor-classes/starter-files/package-lock.json, src/workshops/react-refactor-classes/starter-files/package.json, src/workshops/react-refactor-classes/starter-files/solution/Counter.jsx, src/workshops/react-refactor-classes/starter-files/solution/Keyboard.jsx, src/workshops/react-refactor-classes/starter-files/solution/Pokemon.jsx, src/workshops/react-refactor-classes/starter-files/workshop/Counter.jsx, src/workshops/react-refactor-classes/starter-files/workshop/Keyboard.jsx, src/workshops/react-refactor-classes/starter-files/workshop/Pokemon.jsx
=> React week project

src/course/syllabus/full-stack-app/schedule.md
Anni's talk this week is on Thursday morning so I have changed the Tuesday speaker slot to employment prep and included her talk in the schedule.
=> Update speaker slot and employment prep

src/_includes/course.11ty.js, src/course/syllabus/pre-apprenticeship-2/project.md, src/course/syllabus/pre-apprenticeship-2/resources.md, src/course/syllabus/pre-apprenticeship-2/schedule.md
Add work to do and project for this week
=> Add the schedule for this week

src/course/svelte.md
@Albadylic I'm not sure the project is that interesting, but then again they won't have long so it's more about experimentation than anything else.
=> Add Svelte schedule

src/_includes/course.11ty.js, src/course/syllabus/pre-app-9/learning-outcomes.md, src/course/syllabus/pre-app-9/project.md, src/course/syllabus/pre-app-9/resources.md, src/course/syllabus/pre-app-9/schedule.md, src/course/syllabus/pre-app-9/spikes.md
Week 10 will mostly be TDD Array Methods, the morning challenge and the bulk of the project work.
=> Add Week 9 (testing) to pre-apprenticeship

src/course/syllabus/pre-app-9/learning-outcomes.md, src/course/syllabus/pre-app-9/schedule.md
Employment is going to take up a lot of their time, so we'll spread the work out across the next 4 weeks
=> Remove most work from Week 9

src/course/syllabus/apprenticeship/database/schedule.md
=> Fix gap in FAC22 DB Week Wednesday

src/_includes/components/SidebarNav.js, src/_includes/course.11ty.js
So we don't maintain two copies and let one get out of sync
=> Code of Conduct should link to main FAC site

src/course/syllabus/apprenticeship/authentication/schedule.md, src/course/syllabus/apprenticeship/client-side-app/schedule.md, src/course/syllabus/apprenticeship/database/schedule.md, src/course/syllabus/apprenticeship/full-stack-app/schedule.md, src/course/syllabus/apprenticeship/server-side-app/schedule.md
Add Tech for Better to the schedules, remove employment prep, remove an extra talk and the link to the old ceremonies slides
=> Add TFB, Remove EP

src/_includes/course.11ty.js, src/course/application/approaching-problems.md, src/course/application/approching-problems.md, src/course/application/array-methods.md, src/course/application/building-a-site.md, src/course/application/debugging.md, src/course/application/dom.md, src/course/application/feature.md, src/course/application/flexbox.md, src/course/application/functions.md, src/course/application/git.md, src/course/application/how-to.md, src/course/application/number-functions.md, src/course/application/objects.md, src/course/application/platforms.md
Fixes #492 
- All weekly prompts on the coursebook
- Information on how to complete them, what platforms to use and how to approach problems
- Added to navigation on left of syllabus
=> Application curriculum

src/course/syllabus/apprenticeship/server-side-app/schedule.md
=> Add 15 minute block for presentation on final in-house projects

src/_includes/course.11ty.js, src/course/handbook/user-research.md
Add information regarding user research for in-house projects to the handbook.
=> User research documentation Relates #543 

src/course/syllabus/projects/TFB-build-2/schedule.md
This is what the changes look like:
=> Rejig schedule for last Friday of FAC22 to include Super Cohort SGC

src/course/syllabus/pre-apprenticeship/http/schedule.md, src/course/syllabus/pre-apprenticeship/markup/schedule.md, src/course/syllabus/pre-apprenticeship/testing/schedule.md, src/workshops/css-layout/starter-files/challenge-4/challenge-4.css, src/workshops/css-layout/starter-files/challenge-4/solution.html
=> FAC24 pre-app

src/_data/defaultSchedule.yml, src/course/handbook/user-manuals.md, src/course/syllabus/apprenticeship/authentication/schedule.md, src/course/syllabus/apprenticeship/database/schedule.md, src/course/syllabus/apprenticeship/server/schedule.md
A couple of fixes for the next couple of weeks, also adding in the project-mgmt talks.
=> Fac23 update

src/_includes/course.11ty.js, src/course/handbook/asking-for-help.md
=> Finally write guide on asking for help

src/course/syllabus/pre-apprenticeship/testing/schedule.md
=> Correct SB4 Testing topic dates

src/course/syllabus/apprenticeship/authentication/spikes.md, src/course/syllabus/apprenticeship/database/spikes.md, src/course/syllabus/apprenticeship/server-side-app/spikes.md, src/course/syllabus/apprenticeship/server/spikes.md
following discussion w @oliverjam : keep the tech spikes most relevant to project work.
The following spikes are excluded.
Server : Modules  (already covered in intro talk)
Database: SQL vs noSQL (already covered in intro talk)
Auth: HTTPS/TLS (likely will never implement TLS stuff as a junior dev: hosting providers do it for you)
=> update tech spikes to 3 a week for FAC23

src/course/syllabus/pre-apprenticeship/http/schedule.md, src/course/syllabus/pre-apprenticeship/markup/schedule.md, src/course/syllabus/pre-apprenticeship/testing/schedule.md
=> Update employment prep schedule

src/course/handbook/mentor-guidance.md
Have kept some copy from the old version.
=> rework mentor guidance to be a day by day checklist

src/course/syllabus/projects/TFB-design/schedule.md, src/course/syllabus/projects/TFB-design/spikes.md, src/course/syllabus/projects/in-house-design/schedule.md, src/course/syllabus/projects/in-house-design/spikes.md
- Not so sure about in house design week.. the time after 17:00 seems a little wasted.
=> Design sprint spikes

src/course/syllabus/projects/TFB-build-1/schedule.md
(will make another pr moving code reviews for the other weeks.. just wanted to get this done before pastoral calls today)
=> move code review to thursday

src/_data/eleventyComputed.js, src/course/handbook/installation-checker.sh.njk, src/course/handbook/installation.md
- Add installation checker script to automatically tell you what's missing
- Bump minimum versions of node/npm/psql (time really flies 😓)
- Recommend postgres.app on Macs to avoid Homebrew wrecking stuff
=> Installation checker

src/_data/defaultSchedule.yml, src/course/syllabus/apprenticeship/database/schedule.md
Need to decide what to do with second half - any thoughts? same format?
=> move all code reviews to thursday

src/workshops/git-workflow/index.md
=> Add collaborator in Git Flow workshop

src/course/syllabus/apprenticeship/authentication/schedule.md, src/course/syllabus/apprenticeship/client-side-app/schedule.md, src/course/syllabus/apprenticeship/database/schedule.md, src/course/syllabus/apprenticeship/full-stack-app/schedule.md, src/course/syllabus/apprenticeship/server-side-app/schedule.md, src/course/syllabus/projects/in-house-build-1/schedule.md, src/course/syllabus/projects/in-house-build-2/schedule.md, src/course/syllabus/projects/in-house-design/schedule.md
took 15 mins out of project setup and 15 mins out of the workshop right after tfb (in some cases 30 mins out of build time)
=> increase tfb to 90 minutes

src/course/handbook/mentor-roles.md
=> Remove obsolete mentor roles

src/course/syllabus/apprenticeship/authentication/schedule.md, src/course/syllabus/apprenticeship/server-side-app/schedule.md
Have shortened the express middleware workshop from 3 hours to 2 - would this be enough?
=> Update schedule for bank holiday

src/workshops/express-middleware/index.md
So we can fit it into auth week
=> Remove error-handling from middleware workshop

src/course/handbook/projects.md
=> Warn learners about out of hours project work

src/workshops/react-refactor-classes/starter-files/package.json, src/workshops/react-refactor-classes/starter-files/solution/Pokemon.jsx, src/workshops/react-refactor-classes/starter-files/workshop/Pokemon.jsx
Joe found that tests weren't passing in this workshop because of a syntax error (a getPokemon function was imported when already declared lower down in the file)
Also updated the test command to jest --watchAll because --watch only works for git repos
=> fix tests failing at start

src/course/syllabus/pre-apprenticeship/http/schedule.md
=> New Week 4 schedule

src/_data/defaultSchedule.yml, src/course/handbook/retrospectives.md, src/course/syllabus/apprenticeship/authentication/schedule.md, src/course/syllabus/apprenticeship/database/schedule.md, src/course/syllabus/apprenticeship/server-side-app/schedule.md
Closes https://github.com/orgs/foundersandcoders/projects/7/views/8
=> New friday schedule

src/course/handbook/project-team.md
=> remove po liaison and project documenter roles

src/course/syllabus/apprenticeship/full-stack-app/schedule.md
- Move TFB selection
- Add Digital 101
- Adjust Friday schedule
=> Fixes for FAC24

src/workshops/server-side-forms/index.md
@reubengt do you think this is enough? I feel like the only way to provide any more of the solution would just be giving the whole answer
Fix #620
=> Give stronger hint for server form filter solution

src/course/syllabus/pre-apprenticeship/projects/project.md, src/course/syllabus/pre-apprenticeship/projects/schedule.md, src/workshops/dev-tooling/index.md, src/workshops/node-npm-intro/index.md
- Remove CommonJS module intro from "Node & npm intro" (this will be covered in Server Week)
- Write new guide on Prettier/ESLint/Browsersync (fix #648)
- Add these to SB final 3 weeks schedule
Also relates #698
=> Update Skills Bootcamp Projects schedule

src/course/handbook/mentor-guidance.md
may need more detail around the workshop discussion sessions on tuesdays - @ByteSizedIT to review and add it in once the structure (and do's and don'ts) of these sessions becomes clearer
Closes https://github.com/foundersandcoders/tasks/issues/289
=> rework mentoring guidance for new schedule

src/_data/defaultSchedule.yml, src/course/handbook/user-manuals.md
correct link for Presentation Prep in default schedule; update User Manual section of the course handbook
=> add link for Project in default schedule;

src/_includes/course.11ty.js, src/course/handbook/pair-programming.md
=> Update pairing guidance

src/_includes/workshop.11ty.js, src/learn/server/index.md
Duplicate link to challenge repo at the bottom of workshops to make sure people don't forget about them
=> Challenge reminder

src/learn/server/index.md
Node uses the singular "test" everywhere
=> Fix Node test command/directory

src/course/syllabus/apprenticeship/authentication/schedule.md, src/learn/auth/index.md
I haven't created the associated challenge repo yet.
This new workshop combines 3 previous workshops: [Password security](https://learn.foundersandcoders.com/workshops/password-security/), [Cookie intro](https://learn.foundersandcoders.com/workshops/cookie-auth/), and [Session auth](https://learn.foundersandcoders.com/workshops/session-auth/). It's only slightly longer than _just_ the old Password one, so I've managed to trim things down/simplify a lot.
This is mostly achieved by removing a lot of the "follow along" coding. IMO it didn't make sense to get learners to implement e.g. an insecure way of storing passwords, just to tell them "don't do it like that!" right after.
Instead they'll get practice on these concepts in the associated challenge. This workshop is the walkthrough …
=> Learn authentication

src/learn/form-validation/index.md
Simplifies it a fair bit by removing the challenge parts, which will be in a separate repo.
=> Move form validation workshop to new /learn format

src/course/syllabus/apprenticeship/client-side-app/project.md, src/course/syllabus/apprenticeship/client-side-app/resources.md, src/course/syllabus/apprenticeship/client-side-app/schedule.md, src/learn/react/index.md
Combines "React Components", "React State & Effects" and "React Forms" learning into one resource.
I've edited these down a lot to make the reading more concise; it links to the Beta React Docs in places for more context if people want to dive a bit deeper.
I still need to write the accompanying challenge.
fix #682
=> Combine React learning into one resource

src/course/syllabus/projects/TFB-design/schedule.md
=> Add UT to TFB Design

src/course/handbook/project-docs/product-handover.md, src/course/handbook/project-docs/tfb-presentations.md, src/course/syllabus/projects/TFB-build-2/schedule.md
- Add resources for Product Handover and TFB Presentations
- Reshuffle the last day
Note: I've removed Team SGCs. I'm not sure they're needed for the last week.
=> Update last week of term for FAC25

src/_data/defaultSchedule.yml, src/_includes/course.11ty.js, src/course/syllabus/apprenticeship/authentication/schedule.md, src/course/syllabus/apprenticeship/client-side-app/schedule.md, src/course/syllabus/apprenticeship/database/schedule.md, src/course/syllabus/apprenticeship/full-stack-app/schedule.md, src/course/syllabus/apprenticeship/introduction/learning-outcomes.md, src/course/syllabus/apprenticeship/introduction/project.md, src/course/syllabus/apprenticeship/introduction/resources.md, src/course/syllabus/apprenticeship/introduction/schedule.md, src/course/syllabus/apprenticeship/server-side-app/schedule.md, src/course/syllabus/apprenticeship/server/schedule.md, src/course/syllabus/projects/TFB-build-1/schedule.md, src/course/syllabus/projects/TFB-build-2/schedule.md, src/course/syllabus/projects/TFB-design/schedule.md, src/course/syllabus/projects/in-house-build-1/schedule.md, src/course/syllabus/projects/in-house-build-2/schedule.md, src/course/syllabus/projects/in-house-design/schedule.md
Work in Progress. See also #722 for comments
=> Four day week 2

src/workshops/git-intro/index.md
=> Add GPG error guidance to GitHub intro

src/course/syllabus/application/game/learning-outcomes.md, src/course/syllabus/application/hobby-page/learning-outcomes.md, src/course/syllabus/application/hobby-page/project.md, src/course/syllabus/application/movie-data/learning-outcomes.md, src/course/syllabus/application/movie-data/resources.md, src/course/syllabus/application/project-gallery/learning-outcomes.md, src/course/syllabus/application/website/learning-outcomes.md
Significantly reduce the LO's for the application projects
=> simplify learning outcomes for application projects

src/course/syllabus/projects/in-house-build-1/schedule.md
Reverts foundersandcoders/coursebook#835
=> Revert "temp change schedule to enable early speaker"

src/course/syllabus/apprenticeship/client-side-app/resources.md, src/learn/react/index.md, src/workshops/react-components/index.md, src/workshops/react-forms/index.md, src/workshops/react-state-effects/index.md
Hi! 👋 
The React team finally released the beta docs that have been in development for years, so I thought I'd update all the links in the coursebook.
I also cleaned up the resources tab a bit and removed the old video recommendations as they were all outdated and on paid platforms that learners don't have access to.
=> React docs update

src/course/dot-net.md
=> Intro resources on .NET and Umbraco

src/_data/defaultSchedule.yml, src/course/syllabus/developer/authentication/schedule.md, src/course/syllabus/developer/client-side-app/schedule.md, src/course/syllabus/developer/database/schedule.md, src/course/syllabus/developer/introduction/schedule.md, src/course/syllabus/developer/server-side-app/schedule.md, src/course/syllabus/developer/server/schedule.md
=> Week 3 Schedule changes

.alexignore, .alexrc.js, README.md, package-lock.json, package.json
=> Remark install

src/course/handbook/project-presentations.md, src/course/syllabus/developer/authentication/schedule.md
Add EPA slides to the schedule for this week, awaits https://github.com/foundersandcoders/fac-slides/pull/109 before merging...
=> Add the epa intro to week 3

src/learn/react/index.md
=> Changes in React code so you dont get React 17 error

src/course/handbook/mentor-guidance.md, src/course/handbook/mentor-roles.md
=> Condensed the copy for the mentoring guidance and added styling

src/_data/defaultSchedule.yml, src/_includes/course.11ty.js, src/course/syllabus/developer/authentication/schedule.md, src/course/syllabus/developer/client-side-app/schedule.md, src/course/syllabus/developer/database/schedule.md, src/course/syllabus/developer/introduction/schedule.md, src/course/syllabus/developer/projects/TFB-design/schedule.md, src/course/syllabus/developer/projects/in-house-build-1/schedule.md, src/course/syllabus/developer/projects/in-house-build-2/schedule.md, src/course/syllabus/developer/projects/in-house-design/schedule.md, src/course/syllabus/developer/server-side-app/schedule.md, src/course/syllabus/developer/server/schedule.md, src/course/syllabus/tfb/week 1/content.md, src/course/syllabus/tfb/week 2/content.md, src/course/syllabus/tfb/week 3/content.md
Schedule modified to remove bank holiday and include all of the 'Thought of the Week' sessions
Some small changes to the Tech For Better menu titles and content for weeks 1-3
=> Schedule changes

src/course/syllabus/developer/database/schedule.md
'Thought of the Week' session block corrected to reflect the material delivered
=> updated 'thought of the week' session in week 2

src/course/syllabus/foundation/full-stack/employability.md, src/course/syllabus/foundation/full-stack/schedule.md, src/course/syllabus/foundation/markup/employability.md, src/course/syllabus/foundation/markup/schedule.md, src/course/syllabus/foundation/node/employability.md, src/course/syllabus/foundation/node/schedule.md, src/course/syllabus/foundation/post-course/employability.md, src/course/syllabus/foundation/post-course/post-course.json, src/course/syllabus/foundation/testing/employability.md, src/course/syllabus/foundation/testing/schedule.md
- Add session objectives into employability tabs
- Rename 'weekly quiz' to 'knowledge quiz'
=> Employability

archive/index.md, src/course/syllabus/foundation/full-stack/homework.md, src/course/syllabus/foundation/markup/homework.md, src/course/syllabus/foundation/node/homework.md, src/course/syllabus/foundation/testing/homework.md, src/workshops/node-npm-intro/index.md
I have updated the node workshops. It's pretty similar to before except that I have replaced cowsay with the almost identical figlet. The output is written to a file instead of in the terminal. I think viewing the behaviour in vs code is more intuitive at this stage (vs in the terminal). There are still opportunities to try running code in the terminal.
Feedback welcome
I have created an archive folder which has the old workshop in it. Following a conversation with @sofer  I will be moving any previous versions of pages into here from now on.
=> Update node workshop

archive/foundation /full-stack/learning-outcomes.md, archive/foundation /full-stack/project.md, src/course/syllabus/foundation/full-stack/learning-outcomes.md, src/course/syllabus/foundation/full-stack/project.md, src/course/syllabus/foundation/full-stack/schedule.md
- move previous project and learning outcomes md files to archive
- update full stack project with api mash up project
- create and update full stack learning outcomes
=> update full stack project and learning outcomes

src/course/syllabus/developer/project-1-server/resources.md
- Updates week one resources tab to include resources for typescript, express and restful apis.
=> Updates to resources tab for week one

src/course/syllabus/developer/project-1-server/schedule.md
took the changes from the notion and a few rough guesses at how we might do other things. Not sure what the workshops for friday are going to be
=> first draft

src/course/syllabus/developer/introduction/schedule.md
Makes week 0 match the plan (currently has links sugested typescript site can be replaced if Ollie makes us something)
=> First draft week 0

src/_includes/course.11ty.js, src/course/syllabus/developer/project-1-frontend/schedule.md, src/course/syllabus/developer/project-1-test-deploy/schedule.md, src/course/syllabus/developer/project-2-week-1/learning-outcomes.md, src/course/syllabus/developer/project-2-week-1/project.md, src/course/syllabus/developer/project-2-week-1/resources.md, src/course/syllabus/developer/project-2-week-1/schedule.md, src/course/syllabus/developer/project-2-week-2/learning-outcomes.md, src/course/syllabus/developer/project-2-week-2/project.md, src/course/syllabus/developer/project-2-week-2/resources.md, src/course/syllabus/developer/project-2-week-2/schedule.md
added a link to a relitively short bit of cypress learning that we can accompany with the sugestion they get finished with typescript execute program before the deadline next week
=> Week2 workshop add

src/_includes/course.11ty.js, src/course/syllabus/developer/project-1-test-deploy/schedule.md, src/course/syllabus/developer/project-2-week-1/learning-outcomes.md, src/course/syllabus/developer/project-2-week-1/project.md, src/course/syllabus/developer/project-2-week-1/resources.md, src/course/syllabus/developer/project-2-week-1/schedule.md, src/course/syllabus/developer/project-2-week-2/learning-outcomes.md, src/course/syllabus/developer/project-2-week-2/project.md, src/course/syllabus/developer/project-2-week-2/resources.md, src/course/syllabus/developer/project-2-week-2/schedule.md
updated week 5 there is not link attached to the teraform learning but that can be added when its ready
=> Week 5 update

src/course/syllabus/developer/project-2-week-2/schedule.md, src/course/syllabus/developer/project-2-week-3/learning-outcomes.md, src/course/syllabus/developer/project-2-week-3/project.md, src/course/syllabus/developer/project-2-week-3/resources.md
- Update to all tabs for week 5
- Update the Friday workshop link
=> Updates for tabs for week 5

src/course/syllabus/developer/project-2-week-3/schedule.md, src/learn/DOTNET/index.md
rough draft workshop to go with the challenge repo linked within
=>  added workshop

src/course/syllabus/developer/projects/DOTNET-intro/schedule.md, src/learn/dotnet-two/index.md
added the workshop I have given it a quick spell check but the content and how clear it is I would like a 2nd set of eyes on. Needs to go up by end of day. Also I probably missed at least one thing in my spell check
=> added workshop

src/_includes/course.11ty.js, src/course/syllabus/developer/projects/dotnet-with-testing/learning-outcomes.md, src/course/syllabus/developer/projects/dotnet-with-testing/project.md, src/course/syllabus/developer/projects/dotnet-with-testing/resources.md, src/course/syllabus/developer/projects/dotnet-with-testing/schedule.md
=> schedual for week two of dotnet

src/course/syllabus/developer/projects/DOTNET-intro/resources.md, src/learn/DOTNET/index.md
outside of urls we should not see dotnet anywhere
=> no more dotnet all .NET

src/course/syllabus/developer/projects/project-3-week-3/resources.md
Update to cheat sheet link in the resources tab.
=> Update to link in resources tab

src/course/syllabus/foundation/pre-course/schedule.md
new precourse with more workshops and a stretch
=> updated precoure

src/_data/defaultSchedule.yml, src/course/syllabus/developer/week01-project01-basics/overview.md, src/course/syllabus/developer/week01-project01-basics/schedule.md, src/course/syllabus/developer/week02-project02-chatbot/overview.md, src/course/syllabus/developer/week02-project02-chatbot/resources.md, src/course/syllabus/developer/week03-project03-server/overview.md
updated Ivan's talk
Rescheduled workshops to fit the projects
Schedule won't show same task divided in different boxes
Added week03 overview
Removed repeated/obsolete info/taks from overview (old schedule). Some tasks
=> Fac30 week03

src/_data/defaultSchedule.yml, src/course/syllabus/developer/week03-project03-server/overview.md, src/course/syllabus/developer/week03-project03-server/project.md
Update project description week03
Updated on schedule (added links and talk descriptions)
=> Fac30 week04

src/workshops/functions-callbacks-async/index.md, src/workshops/functions-callbacks-async/starter-files/challenge/stretch/index.html, src/workshops/functions-callbacks-async/starter-files/challenge/stretch/solution.html
Issue #991 
Added array method to async workshop task.
=> Add stretch to async workshop

src/course/syllabus/developer/week09-reading-week/overview.md, src/course/syllabus/developer/week09-reading-week/resources.md, src/course/syllabus/developer/week09-reading-week/week09-reading-week.json
Added .NET workshops and resources for week09
=> Fac30 week09
